const placeholderArticles = [
  {
    "source": {
        "id": "wired",
        "name": "Wired"
    },
    "author": "Nadeem Sarwar, Shreya Fotedar",
    "title": "This Ancient Technology Is Helping Millions Stay Cool",
    "description": "Cheap, low-energy evaporative cooling devices are keeping water, food, people, and even whole buildings cool across India.",
    "url": "https://www.wired.com/story/evaporative-cooling-devices-coolant-clay-matka-mitticool-india-heat-wave/",
    "urlToImage": "https://media.wired.com/photos/6672c421e0704c563b4e7b77/191:100/w_1280,c_limit/GettyImages-80973767.jpg",
    "publishedAt": "2024-07-09T15:42:42Z",
    "content": "CBalance is another company working to tackle the heat problem, specifically for underprivileged households living in tightly packed slums, ghettos, and poorly planned neighborhoods. Led by Vivek Gil… [+3227 chars]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Sarah Fielding",
    "title": "Apple will allow developers access to its NFC technology, avoiding an EU fine",
    "description": "After four years of back and forth, the European Union and Apple have finally come to an agreement on the latter's tap-and-go technology. The European Commission announced Apple made \"legally binding\" commitments to provide developers with their Near-Field Co…",
    "url": "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_5603150f-78f3-420d-a532-a7c962417caa",
    "urlToImage": null,
    "publishedAt": "2024-07-11T12:30:26Z",
    "content": "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"
},
{
    "source": {
        "id": "wired",
        "name": "Wired"
    },
    "author": "Chris Baraniuk",
    "title": "Cutting-Edge Technology Could Massively Reduce the Amount of Energy Used for Air Conditioning",
    "description": "Roughly 10 percent of the world’s energy is used for cooling, with much of the necessary electricity generated by fossil fuels. Companies need to make AC much more efficient—as soon as possible.",
    "url": "https://www.wired.com/story/cutting-edge-technology-could-massively-reduce-the-amount-of-energy-used-for-air-conditioning/",
    "urlToImage": "https://media.wired.com/photos/669567ce4644317579b09a01/191:100/w_1280,c_limit/Medinol%20FMJ%20RED%20(2)%20-%20Credit%20Nostromo%20Energy.png",
    "publishedAt": "2024-07-16T10:00:00Z",
    "content": "The AirJoule system consists of two chambers, each one containing surfaces coated with this special material. They take turns at dehumidifying a flow of air. One chamber is always drying air that is … [+3743 chars]"
},
{
    "source": {
        "id": "wired",
        "name": "Wired"
    },
    "author": "Aarian Marshall",
    "title": "You Won’t Believe What Car Headlights Have in Store",
    "description": "New technology and a drive toward electrified powertrains have converged to create a flashy new car-lighting landscape. What comes next could be an international light language.",
    "url": "https://www.wired.com/story/you-wont-believe-what-car-headlights-have-in-store/",
    "urlToImage": "https://media.wired.com/photos/66ab9e4105e2c8a2510afd5c/191:100/w_1280,c_limit/Lucid%20Headlight%20Rendering%20(1).gif",
    "publishedAt": "2024-08-02T11:00:00Z",
    "content": "Sure, duh: Vehicle lights serve the important and vital safety function of allowing drivers to see where theyre going, and everyone else to see when theyre coming. But for decades, car designers have… [+2972 chars]"
},
{
    "source": {
        "id": "the-verge",
        "name": "The Verge"
    },
    "author": "David Pierce",
    "title": "Go Read This: The Verge’s favorite reads from all over the web",
    "description": "These are the best reads on the web about technology, science, entertainment, gaming, and more, curated by the staff of The Verge.",
    "url": "https://www.theverge.com/24188803/best-tech-reads-articles-books",
    "urlToImage": "https://cdn.vox-cdn.com/thumbor/SddIw5BuFj8hHOaZLhzX9S09KSQ=/0x0:2040x1360/1200x628/filters:focal(1020x680:1021x681)/cdn.vox-cdn.com/uploads/chorus_asset/file/13720553/VRG_ILLO_3180_AI_001.jpg",
    "publishedAt": "2024-07-08T17:58:23Z",
    "content": "The internet is filled with awesome stuff to read, and theres new awesome stuff to read being published every day! Thats the good news. The bad news is that finding the good stuff feels harder than e… [+6401 chars]"
},
{
    "source": {
        "id": null,
        "name": "Gizmodo.com"
    },
    "author": "Lightspeed",
    "title": "Technology Softens a Poignant Farewell in This Sci-Fi Short Story",
    "description": "Take a reading break with \"The Last Lucid Day\" by Dominique Dickey, courtesy of Lightspeed Magazine.",
    "url": "https://gizmodo.com/technology-softens-a-poignant-farewell-in-this-sci-fi-short-story-2000474206",
    "urlToImage": "https://gizmodo.com/app/uploads/2024/07/July_Lightspeed_io9-2-2.jpg",
    "publishedAt": "2024-07-18T22:00:50Z",
    "content": "io9 is proud to present fiction from LIGHTSPEED MAGAZINE. Once a month, we feature a story from LIGHTSPEEDs current issue. This months selection is The Last Lucid Day by Dominique Dickey. Enjoy! (You… [+18277 chars]"
},
{
    "source": {
        "id": null,
        "name": "Gizmodo.com"
    },
    "author": "Cheryl Eddy",
    "title": "In This Exclusive Evil Clip, AI Bedevils a Priest From Beyond the Grave",
    "description": "Wallace Shawn's Father Ignatius tangles with technology in this scene from episode 9, \"How to Build a Chatbot.\"",
    "url": "https://gizmodo.com/in-this-exclusive-evil-clip-ai-bedevils-a-priest-from-beyond-the-grave-2000475909",
    "urlToImage": "https://gizmodo.com/app/uploads/2024/07/EVIL_409_EF_0410_00391_RT-1.jpg",
    "publishedAt": "2024-07-17T20:00:08Z",
    "content": "As Evil oozes its way toward the season four finaleand then wraps up the show forever with a quartet of concluding episodesit’s continued to do what it does best: poke into the horrors of the modern … [+2227 chars]"
},
{
    "source": {
        "id": null,
        "name": "Gizmodo.com"
    },
    "author": "Ed Cara",
    "title": "Period 2.0: Scientists Create Menstrual Pads and Cups That Solidify Blood",
    "description": "Scientists have developed a revolutionary menstrual technology with pads and cups that solidify blood, reducing leaks and environmental impact.",
    "url": "https://gizmodo.com/revolutionizing-menstrual-care-solidify-blood-2000431231",
    "urlToImage": "https://gizmodo.com/app/uploads/2024/07/image-6.jpg",
    "publishedAt": "2024-07-10T15:00:13Z",
    "content": "The future of menstruation may look a bit different than today, if a team of scientists in Virginia have anything to say about it. Theyve created pads and cups that can solidify menstrual blood rathe… [+4260 chars]"
},
{
    "source": {
        "id": null,
        "name": "Gizmodo.com"
    },
    "author": "Matthew Gault",
    "title": "America’s Cyber Security Agency Picks Its First Head of AI",
    "description": "The pick comes at a time when CISA’s head has compared the new technology to nuclear weapons.",
    "url": "https://gizmodo.com/americas-cyber-security-agency-picks-its-first-head-of-ai-2000482281",
    "urlToImage": "https://gizmodo.com/app/uploads/2024/08/LISA.jpg",
    "publishedAt": "2024-08-01T18:00:54Z",
    "content": "Washington D.C. has been scrambling for years to find artificial intelligence experts to navigate a world where LLMs and AI models may supercharge every aspect of our lives. This week the Cybersecuri… [+1897 chars]"
},
{
    "source": {
        "id": null,
        "name": "BBC News"
    },
    "author": null,
    "title": "Steel talks for Starmer's first Wales visit as PM",
    "description": "New Labour government says a better deal is available, but warns fresher technology would cut jobs.",
    "url": "https://www.bbc.com/news/articles/cp08vy1lgnvo",
    "urlToImage": "https://ichef.bbci.co.uk/news/1024/branded_news/de28/live/dc2dce60-3ca3-11ef-b7e6-0509dd8ba4e8.jpg",
    "publishedAt": "2024-07-07T21:00:03Z",
    "content": "Sir Keir Starmer will visit Wales on Monday for the first time since becoming prime minister, with talks focussing on steel job cuts.\r\nHe is expected to meet First Minister Vaughan Gething amid conce… [+1649 chars]"
},
{
    "source": {
        "id": null,
        "name": "Gizmodo.com"
    },
    "author": "Justin Carter",
    "title": "Colin Kaepernick Pisses Off Comics Industry with AI Comics Deal",
    "description": "As is the case with genAI in other industries, comics pros are not happy about the technology intruding on their space.",
    "url": "https://gizmodo.com/colin-kaepernick-lumi-genai-comics-2000482978",
    "urlToImage": "https://gizmodo.com/app/uploads/2024/08/colin-kaepernick.jpg",
    "publishedAt": "2024-08-04T20:30:30Z",
    "content": "The rise of generative AI has caused no small amount of controversy in the last year, particular over in the entertainment industry. It was a big reason for the Hollywood strikes and the current stri… [+2793 chars]"
},
{
    "source": {
        "id": null,
        "name": "BBC News"
    },
    "author": null,
    "title": "Watch: How drones and the battle for Ukraine are changing the future of warfare",
    "description": "Drone technology has made the war more immediate and more deadly – and opened up a new battleground.",
    "url": "https://www.bbc.com/news/videos/cw4y2mrp4jwo",
    "urlToImage": "https://ichef.bbci.co.uk/news/1024/branded_news/a454/live/ed49c290-4aa8-11ef-8f0f-0577398c3339.jpg",
    "publishedAt": "2024-07-25T17:12:13Z",
    "content": "Drones have made the war in Ukraine more immediate and more deadly and opened up a new battleground in Ukraine. \r\nAlmost none of this technology was here in Ukraine a year ago; now it is commonplace.… [+395 chars]"
},
{
    "source": {
        "id": null,
        "name": "MacRumors"
    },
    "author": "Juli Clover",
    "title": "Apple Releases Safari Technology Preview 199 With Bug Fixes and Performance Improvements",
    "description": "Apple today released a new update for Safari Technology Preview, the experimental browser Apple first introduced in March 2016. Apple designed the ‌Safari Technology Preview‌ to test features that may be introduced into future release versions of Safari.\n\n\n\n\n…",
    "url": "https://www.macrumors.com/2024/07/17/apple-releases-safari-technology-preview-199/",
    "urlToImage": "https://images.macrumors.com/t/jHD1aGfXq86Ln_kfzTyWIF68vOo=/2368x/article-new/2021/02/Safari-Technology-Preview-Feature.jpg",
    "publishedAt": "2024-07-17T23:40:22Z",
    "content": "Apple today released a new update for Safari Technology Preview, the experimental browser Apple first introduced in March 2016. Apple designed the ‌Safari Technology Preview‌ to test features that ma… [+923 chars]"
},
{
    "source": {
        "id": null,
        "name": "Slashdot.org"
    },
    "author": "BeauHD",
    "title": "OpenAI Working On New Reasoning Technology Under Code Name 'Strawberry'",
    "description": "OpenAI is close to a breakthrough with a new project called \"Strawberry,\" which aims to enhance its AI models with advanced reasoning abilities. Reuters reports: Teams inside OpenAI are working on Strawberry, according to a copy of a recent internal OpenAI do…",
    "url": "https://tech.slashdot.org/story/24/07/13/0031237/openai-working-on-new-reasoning-technology-under-code-name-strawberry",
    "urlToImage": "https://a.fsdn.com/sd/topics/ai_64.png",
    "publishedAt": "2024-07-13T01:25:00Z",
    "content": "Teams inside OpenAI are working on Strawberry, according to a copy of a recent internal OpenAI document seen by Reuters in May. Reuters could not ascertain the precise date of the document, which det… [+1779 chars]"
},
{
    "source": {
        "id": null,
        "name": "MacRumors"
    },
    "author": "Juli Clover",
    "title": "Apple Releases Safari Technology Preview 200 With Bug Fixes and Performance Improvements",
    "description": "Apple today released a new update for Safari Technology Preview, the experimental browser that was first introduced in March 2016. Apple designed ‌Safari Technology Preview‌ to allow users to test features that are planned for future release versions of the S…",
    "url": "https://www.macrumors.com/2024/07/31/apple-releases-safari-technology-preview-200/",
    "urlToImage": "https://images.macrumors.com/t/gSfA9gdPJTtAYv_7hjK9YByevcM=/2500x/article-new/2024/07/Safari-Technology-Preview-Updated-Feature-1.jpg",
    "publishedAt": "2024-07-31T21:43:02Z",
    "content": "Apple today released a new update for Safari Technology Preview, the experimental browser that was first introduced in March 2016. Apple designed ‌Safari Technology Preview‌ to allow users to test fe… [+1157 chars]"
},
{
    "source": {
        "id": null,
        "name": "NPR"
    },
    "author": "Scott Simon",
    "title": "A cybersecurity glitch triggered a global technology outage",
    "description": "Airports, hospitals, banks, and government agencies are recovering from a failed software update delivered by the cybersecurity company CrowdStrike to Microsoft’s Windows systems.",
    "url": "https://www.npr.org/2024/07/20/nx-s1-5046343/a-cybersecurity-glitch-triggered-a-global-technology-outage",
    "urlToImage": "https://media.npr.org/include/images/facebook-default-wide-s1400-c100.jpg",
    "publishedAt": "2024-07-20T15:09:25Z",
    "content": "Airports, hospitals, banks, and government agencies are recovering from a failed software update delivered by the cybersecurity company CrowdStrike to Microsofts Windows systems."
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Mariella Moon",
    "title": "Paramount and Skydance will merge to create new tech-media giant",
    "description": "David Ellison, the new chief executive of Paramount, has big plans for the media giant and wants to turn it into a \"media and technology\" company, according to the Financial Times. Ellison is taking over as Paramount's boss after his production studio, Skydan…",
    "url": "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_ba12447e-0d80-4028-aa16-3b85313b7749",
    "urlToImage": null,
    "publishedAt": "2024-07-09T14:00:52Z",
    "content": "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"
},
{
    "source": {
        "id": null,
        "name": "MacRumors"
    },
    "author": "Hartley Charlton",
    "title": "Trial Production of Apple's Next-Gen Chip Technology to Begin Next Week",
    "description": "Apple chipmaker TSMC will begin test production of 2nm chips next week ahead of plans to bring the technology to Apple silicon next year, ET News reports.\n\n\n\n\n\nThe trial production run will occur at TSMC's Baoshan plant in northern Taiwan. Equipment designed …",
    "url": "https://www.macrumors.com/2024/07/09/next-gen-chip-trial-to-begin-next-week/",
    "urlToImage": "https://images.macrumors.com/t/J46PnqFon6uZq7AZIAThCrBf36g=/2500x/article-new/2024/04/apple-silicon-feature-joeblue.jpg",
    "publishedAt": "2024-07-09T12:33:24Z",
    "content": "Apple chipmaker TSMC will begin test production of 2nm chips next week ahead of plans to bring the technology to Apple silicon next year, ET News reports.\r\nThe trial production run will occur at TSMC… [+1305 chars]"
},
{
    "source": {
        "id": null,
        "name": "MacRumors"
    },
    "author": "Joe Rossignol",
    "title": "Apple Expected to Adopt Technology That May Pave Way for 2TB iPhones",
    "description": "Taiwanese research firm TrendForce this week said it anticipates that Apple will begin releasing iPhones with quad-level cell (QLC) storage by 2026. This technology could pave the way for iPhones with 2TB of storage in the future.\n\n\n\n\n\nQLC is a denser storage…",
    "url": "https://www.macrumors.com/2024/07/24/iphone-qlc-stroage-rumor/",
    "urlToImage": "https://images.macrumors.com/t/MxyusPhWtzgzus5l3oFUBp732Rs=/2500x/article-new/2023/09/iPhone-15-Pro-Lineup-Feature-White.jpg",
    "publishedAt": "2024-07-24T15:44:18Z",
    "content": "Taiwanese research firm TrendForce this week said it anticipates that Apple will begin releasing iPhones with quad-level cell (QLC) storage by 2026. This technology could pave the way for iPhones wit… [+1291 chars]"
},
{
    "source": {
        "id": null,
        "name": "MacRumors"
    },
    "author": "Joe Rossignol",
    "title": "Apple Expected to Adopt Technology That May Pave Way for 2TB iPhones",
    "description": "Taiwanese research firm TrendForce this week said it anticipates that Apple will begin releasing iPhones with quad-level cell (QLC) storage by 2026. This technology could pave the way for iPhones with 2TB of storage in the future.\n\n\n\n\n\nQLC is a denser storage…",
    "url": "https://www.macrumors.com/2024/07/24/iphone-qlc-storage-rumor/",
    "urlToImage": "https://images.macrumors.com/t/MxyusPhWtzgzus5l3oFUBp732Rs=/2500x/article-new/2023/09/iPhone-15-Pro-Lineup-Feature-White.jpg",
    "publishedAt": "2024-07-24T15:44:18Z",
    "content": "Taiwanese research firm TrendForce this week said it anticipates that Apple will begin releasing iPhones with quad-level cell (QLC) storage by 2026. This technology could pave the way for iPhones wit… [+1291 chars]"
},
{
    "source": {
        "id": null,
        "name": "Gizmodo.com"
    },
    "author": "Lucas Ropek",
    "title": "Taco Bell Is Deploying AI to Screw Up Your Crunchwrap Supreme",
    "description": "The global franchise has announced that it will be integrating AI into the operations of Taco Bell drive-thru locations \"throughout\" the U.S.",
    "url": "https://gizmodo.com/taco-bell-is-deploying-ai-to-screw-up-your-crunchwrap-supreme-2000481954",
    "urlToImage": "https://gizmodo.com/app/uploads/2024/07/shutterstock_2431519893.jpg",
    "publishedAt": "2024-08-01T14:35:04Z",
    "content": "Will your next late-night order of diarrhea fuel be taken by a robot? It’s not totally clear. What we do know is this: new forms of automation are coming to Taco Bell and they’re coming soon.\r\nOn Wed… [+2855 chars]"
},
{
    "source": {
        "id": null,
        "name": "Slashdot.org"
    },
    "author": "BeauHD",
    "title": "'Amazing' New Technology Set To Transform the Search For Alien Life",
    "description": "Robin McKie writes via The Guardian: Scientists with Breakthrough Listen, the world's largest scientific research program dedicated to finding alien civilizations, say a host of technological developments are about to transform the search for intelligent life…",
    "url": "https://science.slashdot.org/story/24/07/17/0142204/amazing-new-technology-set-to-transform-the-search-for-alien-life",
    "urlToImage": "https://a.fsdn.com/sd/topics/scifi_64.png",
    "publishedAt": "2024-07-17T10:00:00Z",
    "content": "Scientists with Breakthrough Listen, the world's largest scientific research program dedicated to finding alien civilizations, say a host of technological developments are about to transform the sear… [+2076 chars]"
},
{
    "source": {
        "id": null,
        "name": "Slashdot.org"
    },
    "author": "BeauHD",
    "title": "Cutting-Edge Technology Could Massively Reduce the Amount of Energy Used For Air Conditioning",
    "description": "An anonymous reader quotes a report from Wired, written by Chris Baraniuk: The buses struggling in China's muggy weather gave [Matt Jore, CEO of Montana Technologies] and his colleagues an idea. If they could make dehumidification more efficient somehow, then…",
    "url": "https://tech.slashdot.org/story/24/07/16/2112235/cutting-edge-technology-could-massively-reduce-the-amount-of-energy-used-for-air-conditioning",
    "urlToImage": "https://a.fsdn.com/sd/topics/power_64.png",
    "publishedAt": "2024-07-16T23:20:00Z",
    "content": "The buses struggling in China's muggy weather gave [Matt Jore, CEO of Montana Technologies] and his colleagues an idea. If they could make dehumidification more efficient somehow, then they could mak… [+2648 chars]"
},
{
    "source": {
        "id": "business-insider",
        "name": "Business Insider"
    },
    "author": "Chris Stokel-Walker",
    "title": "How 5G technology is helping curb carbon emissions and waste at the Paris Games",
    "description": "Historically, the Olympic Games have hurt host cities' environments. 5G technology, which requires less physical space and energy, could help.",
    "url": "https://www.businessinsider.com/paris-olympics-how-5g-tech-could-curb-environmental-impact-2024-7",
    "urlToImage": "https://i.insider.com/66a27ce82d66759f66fe52c0?width=1200&format=jpeg",
    "publishedAt": "2024-07-29T15:24:40Z",
    "content": "In August, athletes swam in the Seine as part of a test event for the Paris Games.Michel Euler/ AP\r\n<ul><li>The Games' need for a massive infrastructure project has historically hurt host cities' env… [+6616 chars]"
},
{
    "source": {
        "id": null,
        "name": "Harvard Business Review"
    },
    "author": null,
    "title": "How EdTech Firm Coursera Is Incorporating GenAI into Its Products and Services",
    "description": "How can Coursera continuously improve its GenAI-enabled offerings to stay competitive as the technology evolves?",
    "url": "https://hbr.org/podcast/2024/08/how-edtech-firm-coursera-is-incorporating-genai-into-its-products-and-services",
    "urlToImage": "https://hbr.org/resources/images/article_assets/2023/04/wide-cold-call-hbr.png",
    "publishedAt": "2024-08-06T13:22:00Z",
    "content": "BRIAN KENNY:  Since ChatGPT appeared on the scene back in the fall of 2022, newsfeeds have been flooded with claims that generative AI is going to change the world, so if you’re suffering from a bit … [+29581 chars]"
},
{
    "source": {
        "id": null,
        "name": "CNET"
    },
    "author": "Jesse Orrall",
    "title": "What It's Like Using a Brain Implant With ChatGPT video",
    "description": "We spoke to two people pioneering ChatGPT's integration with Synchron's brain-computer-interface, to learn what it's like to use and where this technology is headed.",
    "url": "https://www.cnet.com/videos/what-its-like-using-a-brain-implant-with-chatgpt/",
    "urlToImage": "https://www.cnet.com/a/img/resize/d7470b4a87611c4ae3a0eb1e683922a5747e724c/hub/2024/07/26/24c1cc8a-a760-4f1a-820e-3f75211a2f98/wtf-synchron-brain-implant-site.jpg?auto=webp&fit=crop&height=675&width=1200",
    "publishedAt": "2024-07-28T12:00:03Z",
    "content": ""
},
{
    "source": {
        "id": null,
        "name": "CNET"
    },
    "author": "Jesse Orrall",
    "title": "How This Brain Implant Is Using ChatGPT",
    "description": "We spoke to two people pioneering ChatGPT's integration with Synchron's brain-computer-interface, to learn what it's like to use and where this technology is headed.",
    "url": "https://www.cnet.com/tech/computing/how-this-brain-implant-is-using-chatgpt/",
    "urlToImage": "https://www.cnet.com/a/img/resize/ac42110f27cd78a7816194b9ca81dd37a519df3e/hub/2024/07/26/91692987-1cfe-4010-9cac-a3163f2c6461/mark.jpg?auto=webp&fit=crop&height=675&width=1200",
    "publishedAt": "2024-07-28T12:00:32Z",
    "content": "One of the leading-edge implantable brain-computer-interface, or BCI, companies is experimenting with ChatGPT integration to make it easier for people living with paralysis to control their digital d… [+3872 chars]"
},
{
    "source": {
        "id": "business-insider",
        "name": "Business Insider"
    },
    "author": "Chris Stokel-Walker",
    "title": "The Olympics will challenge mobile-network providers to satiate 15 million attendees' hunger for internet connectivity",
    "description": "The French telecommunications company Orange is outfitting Paris venues and the Seine with 5G technology for 15 million users.",
    "url": "https://www.businessinsider.com/paris-olympics-internet-connection-5g-mobile-technology-2024-7",
    "urlToImage": "https://i.insider.com/6697fe03fb2b6bedb057f383?width=1200&format=jpeg",
    "publishedAt": "2024-07-25T15:39:35Z",
    "content": "Pierre Mauroy Stadium.Mimpki/Shutterstock\r\n<ul><li>The Olympics will challenge wireless providers as 15 million people seek internet access at once.</li><li>Careful planning and 5G infrastructure lik… [+7432 chars]"
},
{
    "source": {
        "id": null,
        "name": "CNET"
    },
    "author": "Bella Czajkowski",
    "title": "Samsung S90D OLED TV: Sleek Design Complements Great Picture Quality",
    "description": "Samsung's entry-level OLED TV is substantially less expensive than the S95D, but it lacks the new glare-free technology of the higher-end model.",
    "url": "https://www.cnet.com/tech/home-entertainment/samsung-s90d-oled-tv-sleek-design-complements-great-picture-quality/",
    "urlToImage": "https://www.cnet.com/a/img/resize/77e5cb2488f3a56b7bb2265b5818a0b9110387f5/hub/2024/07/16/e9c133a6-78c4-4306-8b0f-8b9dbdc9c526/samsung-and-lg-tv-remotes.jpg?auto=webp&fit=crop&height=675&width=1200",
    "publishedAt": "2024-07-25T11:00:08Z",
    "content": "Each year, OLEDs are the best (and most expensive) TVs we test in CNET's TV lab. For this review, we lined up Samsung's S90D alongside the company's higher-end OLED, the S95D. The more-expensive Sams… [+11208 chars]"
},
{
    "source": {
        "id": null,
        "name": "[Removed]"
    },
    "author": null,
    "title": "[Removed]",
    "description": "[Removed]",
    "url": "https://removed.com",
    "urlToImage": null,
    "publishedAt": "1970-01-01T00:00:00Z",
    "content": "[Removed]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "The Associated Press",
    "title": "Internet outage latest | Airlines, businesses hit by global technology disruption",
    "description": "An internet outage affecting Microsoft is disrupting flights, banks, media outlets and companies across the world, with problems continuing hours after the...",
    "url": "https://www.yahoo.com/news/internet-outage-latest-airlines-businesses-095702111.html",
    "urlToImage": "https://s.yimg.com/ny/api/res/1.2/_Vrpb1QsZ0Q0lUxVr_FKUA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/ap.org/f26c720841b05245d6a4ff2f74a26e44",
    "publishedAt": "2024-07-19T09:57:02Z",
    "content": "An internet outage affecting Microsoft is disrupting flights, banks, media outlets and companies across the world, with problems continuing hours after the technology company said it was gradually fi… [+6081 chars]"
},
{
    "source": {
        "id": "wired",
        "name": "Wired"
    },
    "author": "Lauren Goode",
    "title": "Open Source AI Has Founders—and the FTC—Buzzing",
    "description": "DC went to YC to talk OS.",
    "url": "https://www.wired.com/story/open-source-ai-y-combinator/",
    "urlToImage": "https://media.wired.com/photos/66a403f38137c57a9c52cc3d/191:100/w_1280,c_limit/Founders-Open-Source-AI-Business.jpg",
    "publishedAt": "2024-07-26T21:56:06Z",
    "content": "Many of yesterdays talks were littered with the acronyms youd expect from this assemblage of high-minded panelists: YC, FTC, AI, LLMs. But threaded throughout the conversationsfoundational to them, y… [+4037 chars]"
},
{
    "source": {
        "id": "the-verge",
        "name": "The Verge"
    },
    "author": "Aude White",
    "title": "The first all-quadriplegic esports team levels the playing field",
    "description": "Director Jess Jacklin talks to The Verge about her new documentary and how she entered the world of competitive esports.",
    "url": "https://www.theverge.com/24195198/quad-gods-documentary-jess-jacklin-interview",
    "urlToImage": "https://cdn.vox-cdn.com/thumbor/cS_pxOIoEaB5DDUl7Q-_tskOGX0=/0x0:980x552/1200x628/filters:focal(490x276:491x277)/cdn.vox-cdn.com/uploads/chorus_asset/file/25524067/richard_jacobs_left_sergio_acevedo_right_.jpg",
    "publishedAt": "2024-07-10T15:00:00Z",
    "content": "Courtesy of HBO\r\n\n \n\n\n Director Jess Jacklin talks to The Verge about her new documentary following the first all-quadriplegic esports team. “All of us have the experience of being a prisoner in your… [+9324 chars]"
},
{
    "source": {
        "id": "wired",
        "name": "Wired"
    },
    "author": "Will Knight",
    "title": "To Lead in AI, the US Needs a Silicon Revolution",
    "description": "US Commerce Department undersecretary Laurie E. Locascio says America needs to invent new chip manufacturing techniques.",
    "url": "https://www.wired.com/story/laurie-locascio-interview-ai-silicon-revolution/",
    "urlToImage": "https://media.wired.com/photos/66aa975f20b0927818d24e50/191:100/w_1280,c_limit/FF-Newsletter-Chips-America-Business.jpg",
    "publishedAt": "2024-08-01T16:00:00Z",
    "content": "One thing that US politicians seem to agree on, despite a great many other differences, is that the country needs to lead technologically to maintain a position of economic and geopolitical preeminen… [+3540 chars]"
},
{
    "source": {
        "id": null,
        "name": "MacRumors"
    },
    "author": "Joe Rossignol",
    "title": "iPad Pro's Tandem OLED Display Tech Could Extend to Future Vision Pro",
    "description": "LG and Samsung have prototyped micro-OLED displays with tandem OLED technology, according to Korean publication Sisa Journal, paving the way for a future model of Apple's Vision Pro mixed-reality headset to potentially adopt the technology.\n\n\n\n\n\nThe report sa…",
    "url": "https://www.macrumors.com/2024/07/31/vision-pro-tandem-oled-report/",
    "urlToImage": "https://images.macrumors.com/t/XMoYyiLjJ3ePlW78tYaibrUAbjs=/2000x/article-new/2023/06/apple-vision-pro-lenses.jpg",
    "publishedAt": "2024-07-31T14:34:44Z",
    "content": "LG and Samsung have prototyped micro-OLED displays with tandem OLED technology, according to Korean publication Sisa Journal, paving the way for a future model of Apple's Vision Pro mixed-reality hea… [+1504 chars]"
},
{
    "source": {
        "id": null,
        "name": "ReadWrite"
    },
    "author": "Sophie Atkinson",
    "title": "Flight-free travel business Byway raises $6 million to improve AI usage and expand the technology",
    "description": "A travel business that deploys AI software to help people book package vacations is announcing the close of an oversubscribed… Continue reading Flight-free travel business Byway raises $6 million to improve AI usage and expand the technology\nThe post Flight-f…",
    "url": "https://readwrite.com/flight-free-travel-business-byway-raises-6-million-to-improve-ai-usage-and-expand-the-technology/",
    "urlToImage": "https://readwrite.com/wp-content/uploads/2024/07/Travel-scaled.jpg",
    "publishedAt": "2024-07-09T10:33:48Z",
    "content": "A travel business that deploys AI software to help people book package vacations is announcing the close of an oversubscribed £5.04 million (roughly $6.45M) Series A round.\r\nHeartcore Capital has led… [+2508 chars]"
},
{
    "source": {
        "id": null,
        "name": "ReadWrite"
    },
    "author": "Alvin Hemedez",
    "title": "AI-Powered Crypto Presale with Predictive Technology – Last Chance to Invest",
    "description": "WienerAI is rapidly gaining traction in the crypto space, and recent developments have only bolstered the project’s appeal. For those… Continue reading AI-Powered Crypto Presale with Predictive Technology – Last Chance to Invest\nThe post AI-Powered Crypto Pre…",
    "url": "https://readwrite.com/ai-powered-crypto-presale-with-predictive-technology-last-chance-to-invest/",
    "urlToImage": "https://readwrite.com/wp-content/uploads/2024/07/ai-powered-crypto-presale-with-predictive-tech-last-chance-to-invest.jpg",
    "publishedAt": "2024-07-23T17:00:18Z",
    "content": "WienerAI is rapidly gaining traction in the crypto space, and recent developments have only bolstered the project’s appeal.\r\nFor those who missed the initial opportunity to invest, there is one final… [+4174 chars]"
},
{
    "source": {
        "id": null,
        "name": "Design-milk.com"
    },
    "author": "Joseph Sgambati III",
    "title": "Beflo’s Tenon Smart Adjustable Desk Rises to the Occasion",
    "description": "Freed from banality, Beflo's Tenon Smart Adjustable Desk reconciles functionality and technology with nuanced, Scandi-like aesthetics.",
    "url": "https://design-milk.com/beflos-tenon-smart-adjustable-desk-rises-to-the-occasion/",
    "urlToImage": "https://design-milk.com/images/2024/06/Beflo-Tenon-Standing-Desk-03.jpg",
    "publishedAt": "2024-07-29T15:00:01Z",
    "content": "The traditional standing desk is nothing new, with historical records indicating its use as early as the 1400s. Great minds like Leonardo da Vinci are said to have utilized something like it in his c… [+3786 chars]"
},
{
    "source": {
        "id": "business-insider",
        "name": "Business Insider"
    },
    "author": "Nora Redmond",
    "title": "A school used facial recognition tech for cafeteria payments. An internet law expert says it's rarely worth the risk.",
    "description": "A UK school broke the law by using facial recognition technology in its cafeteria without assessing the risks to the children's data.",
    "url": "https://www.businessinsider.com/facial-recognition-tech-school-cafeteria-breaks-law-data-risks-raised-2024-7",
    "urlToImage": "https://i.insider.com/66a902f3fb6d32635ee4e57a?width=1200&format=jpeg",
    "publishedAt": "2024-07-31T12:34:12Z",
    "content": "A high school in southeast England illegally used facial recognition technology to take cashless lunch payments from students aged 11-18.Tetra Images via Getty Images\r\n<ul><li>A school in England bro… [+2439 chars]"
},
{
    "source": {
        "id": "business-insider",
        "name": "Business Insider"
    },
    "author": "Charissa Cheong",
    "title": "I work at Microsoft and didn't realize how evil tech can be until I had kids. Here's how I limit their screen use to 1 hour a day.",
    "description": "A Big Tech employee said even he's worried about how technology is impacting his children. Here's how he limits their screen time to one hour a day.",
    "url": "https://www.businessinsider.com/microsoft-dad-limits-kids-screen-time-social-media-2024-8",
    "urlToImage": "https://i.insider.com/66b0d005b4912df3ae18dc6e?width=1200&format=jpeg",
    "publishedAt": "2024-08-06T09:55:56Z",
    "content": "Bill Safcik told BI he wants to monitor his children's digital activity until they turn 18.William Safcik\r\n<ul><li>Bill Safcik, a father of four, has worked at Microsoft for more than 20 years.</li><… [+6520 chars]"
},
{
    "source": {
        "id": "business-insider",
        "name": "Business Insider"
    },
    "author": "Shubhangi Goel",
    "title": "Tesla's biggest competitor just announced a collab with Uber",
    "description": "Uber drivers could get discounts on 100,000 electric vehicles in various markets, and the companies are working on self-driving technology.",
    "url": "https://www.businessinsider.com/byd-uber-partnership-electric-vehicles-discount-autonomous-self-driving-tesla-2024-8",
    "urlToImage": "https://i.insider.com/66838523268f62ba18a67d06?width=1200&format=jpeg",
    "publishedAt": "2024-08-01T05:48:06Z",
    "content": "The deal will bring 100,000 new electric vehicles from BYD onto Uber's platform.Fabrice Coffrini/AFP via Getty Images\r\n<ul><li>BYD said it's partnering with Uber for drivers to lease 100,000 electric… [+3528 chars]"
},
{
    "source": {
        "id": "business-insider",
        "name": "Business Insider"
    },
    "author": "Alistair Barr",
    "title": "AI was supposed to revolutionize customer service. Morgan Stanley's interns aren't buying it.",
    "description": "The bank surveys its interns on their technology habits and views. What they said about AI customer service is another warning for the tech industry.",
    "url": "https://www.businessinsider.com/ai-customer-service-morgan-stanley-interns-2024-8",
    "urlToImage": "https://i.insider.com/66b27788a5247369a3e9e68f?width=1200&format=jpeg",
    "publishedAt": "2024-08-06T20:15:00Z",
    "content": "Maskot/ Getty Images\r\n<ul><li>AI has been touted as a great way to make customer service call centers more efficient.</li><li>Morgan Stanley asked its (human) interns about this. </li><li>Their answe… [+2791 chars]"
},
{
    "source": {
        "id": null,
        "name": "BBC News"
    },
    "author": null,
    "title": "Microsoft apologises after thousands report new outage",
    "description": "Microsoft said it was looking at a 'network infrastructure' issue impacting its services.",
    "url": "https://www.bbc.com/news/articles/c903e793w74o",
    "urlToImage": "https://ichef.bbci.co.uk/news/1024/branded_news/8c6a/live/f7380690-4e7c-11ef-ba22-a972f50cc540.jpg",
    "publishedAt": "2024-07-30T14:28:34Z",
    "content": "Technology giant Microsoft has apologised after thousands in the UK reported issues with its products, ranging from email service Outlook to the hit game Minecraft.\r\nDowndetector, which tracks websit… [+733 chars]"
},
{
    "source": {
        "id": "wired",
        "name": "Wired"
    },
    "author": "Eric Geller",
    "title": "A Senate Bill Would Radically Improve Voting Machine Security",
    "description": "This year’s Intelligence Authorization Act would mandate penetration testing for federally certified voting machines and allow independent researchers to work on exposing vulnerabilities.",
    "url": "https://www.wired.com/story/a-senate-bill-would-radically-improve-voting-machine-security/",
    "urlToImage": "https://media.wired.com/photos/66a810b1ba1b338ccbfd93ac/191:100/w_1280,c_limit/Voting%20Machine%20b_GettyImages-1434792666.jpg",
    "publishedAt": "2024-07-30T14:20:51Z",
    "content": "Congress is moving closer to putting Americas election technology under a stricter cybersecurity microscope.\r\nEmbedded inside this years Intelligence Authorization Act, which funds intelligence agenc… [+3343 chars]"
},
{
    "source": {
        "id": null,
        "name": "[Removed]"
    },
    "author": null,
    "title": "[Removed]",
    "description": "[Removed]",
    "url": "https://removed.com",
    "urlToImage": null,
    "publishedAt": "1970-01-01T00:00:00Z",
    "content": "[Removed]"
},
{
    "source": {
        "id": "the-verge",
        "name": "The Verge"
    },
    "author": "Jay Peters",
    "title": "Xbox Live is down",
    "description": "Microsoft has confirmed a “major outage” is occurring on Xbox Live, blocking players from signing in to their accounts or connecting to any online games.",
    "url": "https://www.theverge.com/2024/7/18/24201568/xbox-live-down-outage-account-sign-in-error",
    "urlToImage": "https://cdn.vox-cdn.com/thumbor/K3xDsKYhhEIhOsqy1PgWTSawZmM=/0x0:2040x1360/1200x628/filters:focal(1020x680:1021x681)/cdn.vox-cdn.com/uploads/chorus_asset/file/25485114/STK048_XBOX2__A.png",
    "publishedAt": "2024-07-18T23:16:51Z",
    "content": "Xbox Live is down\r\nXbox Live is down\r\n / Microsofts Xbox platform went down Thursday night, with many players unable to sign in or connect to online games.\r\nByJay Peters, a news editor who writes abo… [+1221 chars]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Mat Smith",
    "title": "The Morning After: Dune-inspired spacesuit recycles astronauts’ urine into drinkable water",
    "description": "A new space suit designed by scientists at Weill Cornell Medicine and Cornell University, inspired by Frank Herbert’s Dune, could make spacewalks longer and less disgusting by recycling expelled urine in a special filtration backpack.\nThe traditional NASA spa…",
    "url": "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_4a6682cf-6fa1-45d2-8efe-04d87bf836fe",
    "urlToImage": null,
    "publishedAt": "2024-07-15T11:15:40Z",
    "content": "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Cheyenne MacDonald",
    "title": "OpenAI whistleblowers call for SEC probe into NDAs that kept employees from speaking out on safety risks",
    "description": "OpenAI’s NDAs are once again under scrutiny after whistleblowers penned a letter to the SEC alleging that employees were made to sign “illegally restrictive” agreements preventing them from speaking out on the potential harms of the company’s technology. The …",
    "url": "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_4165ad5a-ffbd-4e26-a506-58f4080a02ad",
    "urlToImage": null,
    "publishedAt": "2024-07-13T17:16:04Z",
    "content": "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"
},
{
    "source": {
        "id": null,
        "name": "VentureBeat"
    },
    "author": "Jeremiah Stone, SnapLogic",
    "title": "Unifying gen X, Y, Z and boomers: The overlooked secret to AI success",
    "description": "One critical (but overlooked) facet to gen AI success is the people behind the technology and the dynamics between them.",
    "url": "https://venturebeat.com/ai/unifying-gen-x-y-z-and-boomers-the-overlooked-secret-to-ai-success/",
    "urlToImage": "https://venturebeat.com/wp-content/uploads/2024/07/DDM.png?w=1024?w=1200&strip=all",
    "publishedAt": "2024-07-27T19:05:00Z",
    "content": "Join our daily and weekly newsletters for the latest updates and exclusive content on industry-leading AI coverage. Learn More\r\nModern organizations are acutely aware of the need to effectively lever… [+7497 chars]"
},
{
    "source": {
        "id": null,
        "name": "Design-milk.com"
    },
    "author": "Caroline Williamson",
    "title": "Reimagining the Travel Experience With Biophilia in Singapore’s Changi Airport",
    "description": "BOIFFILS Architectures’ redesign of Changi Airport’s Terminal 2 blends biophilic elements and technology to create a serene, nature-inspired travel experience prioritizing passenger comfort.",
    "url": "https://design-milk.com/reimagining-the-travel-experience-with-biophilia-in-singapores-changi-airport/",
    "urlToImage": "https://design-milk.com/images/2024/07/Singapore-Airport-Changi-Terminal-BOIFFILS-Garden-City-2.jpg",
    "publishedAt": "2024-07-09T16:00:34Z",
    "content": "BOIFFILS Architectures has unveiled its transformative redesign of Terminal 2 at Singapore’s Changi Airport, encapsulating the ‘Garden City’ ethos within a biophilic framework that aims to revolution… [+4960 chars]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Kristen Lawrence",
    "title": "Engineering firm develops game-changing solution for floating offshore wind industry: 'Challenging the status quo'",
    "description": "The technology clearly impressed industry leaders and investors.",
    "url": "https://www.yahoo.com/tech/engineering-firm-develops-game-changing-040000503.html",
    "urlToImage": "https://s.yimg.com/ny/api/res/1.2/xfKUKlio9je3e6URPUwdZA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03ODk-/https://media.zenfs.com/en/the_cool_down_737/dbe9c62759cebbf15b9e66047d141763",
    "publishedAt": "2024-07-15T04:00:00Z",
    "content": "Blackfish Engineering, a United Kingdombased engineering firm specializing in sustainable energy design and development, recently unveiled a mooring system that could be a game-changer for numerous f… [+3421 chars]"
},
{
    "source": {
        "id": null,
        "name": "Gizmodo.com"
    },
    "author": "Sherri L Smith",
    "title": "Logitech CEO Wants to Sell You a Subscription-Based ‘Forever Mouse’",
    "description": "Logitech CEO lays out the potential future of the mouse and keyboard. Logitech is working on a forever mouse that has a subscription-based model.",
    "url": "https://gizmodo.com/logitech-ceo-wants-to-sell-you-a-subscription-based-forever-mouse-2000480678",
    "urlToImage": "https://gizmodo.com/app/uploads/2024/07/Logitech-M240-Silent-Bluetooth-Mouse.jpeg",
    "publishedAt": "2024-07-29T18:55:59Z",
    "content": "During a recent episode of The Verge’s Decoder podcast, Logitech CEO Hanneke Faber shed some possible insight into the company’s view on one of its most important products. Saying that “the mouse bui… [+2097 chars]"
},
{
    "source": {
        "id": null,
        "name": "VentureBeat"
    },
    "author": "Sean Michael Kerner",
    "title": "Salesforce debuts Einstein Service Agent, a new AI Agent for customer self-service",
    "description": "Salesforce is growing its Einstein platform with an autonomous AI agent technology that will be used initially to support customer self-service.",
    "url": "https://venturebeat.com/ai/salesforce-debuts-einstein-service-agent-a-new-ai-agent-for-customer-self-service/",
    "urlToImage": "https://venturebeat.com/wp-content/uploads/2024/07/Einstein_as_a_customer_service_agent_illustration_8k_png2.png?w=1024?w=1200&strip=all",
    "publishedAt": "2024-07-17T12:00:00Z",
    "content": "Join our daily and weekly newsletters for the latest updates and exclusive content on industry-leading AI coverage. Learn More\r\nSalesforce is jumping into the AI agent world with a new service that b… [+4592 chars]"
},
{
    "source": {
        "id": null,
        "name": "VentureBeat"
    },
    "author": "Jordan Fragen",
    "title": "Dotplay raises $1M for web-based mobile game tech platform",
    "description": "Dotplay raised $1M in pre-seed funding for its web-based mobile game technology platform that allows developers to bypass app stores.",
    "url": "https://venturebeat.com/games/dotplay-1m-preseed-funding-mobile-web-gaming/",
    "urlToImage": "https://venturebeat.com/wp-content/uploads/2024/07/Untitled-design-4.png?w=1024?w=1200&strip=all",
    "publishedAt": "2024-07-29T19:11:43Z",
    "content": "GamesBeat is excited to partner with Lil Snack to have customized games just for our audience! We know as gamers ourselves, this is an exciting way to engage through play with the GamesBeat content y… [+1724 chars]"
},
{
    "source": {
        "id": "the-verge",
        "name": "The Verge"
    },
    "author": "Jay Peters",
    "title": "Balatro is getting a free ‘major gameplay update’ in 2025",
    "description": "Balatro, the delightful poker roguelike, will be getting a free “major gameplay update” in 2025, according to developer LocalThunk.",
    "url": "https://www.theverge.com/2024/8/7/24215342/balatro-free-major-gameplay-update-2025",
    "urlToImage": "https://cdn.vox-cdn.com/thumbor/vtP70rjunRnffGkS_-v0SPrAPBU=/0x0:1920x1080/1200x628/filters:focal(960x540:961x541)/cdn.vox-cdn.com/uploads/chorus_asset/file/25563187/370bce44dde6727b566a5bc1821a947521a2fbe7.png",
    "publishedAt": "2024-08-07T15:48:18Z",
    "content": "Balatro is getting a free major gameplay update in 2025\r\nBalatro is getting a free major gameplay update in 2025\r\n / The update will bring new ideas and strategies to the game.\r\nByJay Peters, a news … [+1701 chars]"
},
{
    "source": {
        "id": "the-verge",
        "name": "The Verge"
    },
    "author": "Umar Shakir",
    "title": "NASA blew up this inflatable space station structure on purpose",
    "description": "The second full-scale burst test for Sierra Space’s inflatable LIFE space habitat reached 74 PSI, exceeding NASA’s recommended safety levels.",
    "url": "https://www.theverge.com/2024/7/25/24206219/nasa-sierra-space-inflatable-fabric-space-station-burst-test-video",
    "urlToImage": "https://cdn.vox-cdn.com/thumbor/N_4hGOGCzGdoSS2XM2KYb2Zu7f0=/0x0:8368x5579/1200x628/filters:focal(4184x2790:4185x2791)/cdn.vox-cdn.com/uploads/chorus_asset/file/25545878/Image_2.jpg",
    "publishedAt": "2024-07-25T20:21:42Z",
    "content": "NASA blew up this inflatable space station structure on purpose\r\nNASA blew up this inflatable space station structure on purpose\r\n / Watch Sierra Spaces inflatable space habitat undergo its second Ul… [+1579 chars]"
},
{
    "source": {
        "id": "fox-news",
        "name": "Fox News"
    },
    "author": "Kurt Knutsson, CyberGuy Report",
    "title": "New technology makes it nearly impossible to kill house plants",
    "description": "SmartyPlants monitors your houseplants' light, humidity, temperature, soil moisture and nutrients and sends the information straight to a cellphone app.",
    "url": "https://www.foxnews.com/tech/new-technology-makes-nearly-impossible-kill-house-plants",
    "urlToImage": "https://static.foxnews.com/foxnews.com/content/uploads/2024/07/3-End-houseplant-heartbreak-with-this-new-high-tech-device.jpg",
    "publishedAt": "2024-07-25T10:00:29Z",
    "content": "Remember that \"pandemic garden\" you started in 2020 that didn't quite make it? \r\nWell, you're not alone in your plant care struggles. In fact, many people unintentionally send their houseplants to th… [+5376 chars]"
},
{
    "source": {
        "id": null,
        "name": "The Atlantic"
    },
    "author": "Charlie Warzel",
    "title": "AI Has Become a Technology of Faith",
    "description": "Sam Altman and Arianna Huffington told me that they believe generative AI can help millions of suffering people. I’m not so sure.",
    "url": "https://www.theatlantic.com/technology/archive/2024/07/thrive-ai-health-huffington-altman-faith/678984/?utm_source=feed",
    "urlToImage": null,
    "publishedAt": "2024-07-12T19:21:53Z",
    "content": "An important thing to realize about the grandest conversations surrounding AI is that, most of the time, everyone is making things up. This isn’t to say that people have no idea what they’re talking … [+12977 chars]"
},
{
    "source": {
        "id": null,
        "name": "[Removed]"
    },
    "author": null,
    "title": "[Removed]",
    "description": "[Removed]",
    "url": "https://removed.com",
    "urlToImage": null,
    "publishedAt": "1970-01-01T00:00:00Z",
    "content": "[Removed]"
},
{
    "source": {
        "id": null,
        "name": "Seths.blog"
    },
    "author": "Seth Godin",
    "title": "The page-a-day calendar",
    "description": "Time passes. And humans have always kept track. Distribution and technology combined to create a few decades where the tear off daily calendar was nearly ubiquitous (read on for details on my new one, a collaboration with Debbie Millman). First, the industry …",
    "url": "https://seths.blog/2024/07/the-page-a-day-calendar/",
    "urlToImage": "https://seths.blog/wp-content/uploads/2018/06/seth_godin_ogimages_v02_18061313.jpg",
    "publishedAt": "2024-07-15T08:27:00Z",
    "content": "Time passes. And humans have always kept track.\r\nDistribution and technology combined to create a few decades where the tear off daily calendar was nearly ubiquitous (read on for details on my new on… [+2027 chars]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Cheyenne MacDonald",
    "title": "OpenAI is reportedly working on more advanced AI models capable of reasoning and ‘deep research’",
    "description": "A new report from Reuters\r\n claims OpenAI is developing technology to bring advanced reasoning capabilities to its AI models under a secret project code-named “Strawberry.” Among the project’s goals is to enable the company’s AI models to autonomously scour t…",
    "url": "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_48ff4899-a40a-45e8-990e-529dac3203a7",
    "urlToImage": null,
    "publishedAt": "2024-07-13T20:24:19Z",
    "content": "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Amy Skorheim",
    "title": "The best Amazon Prime Day deals on kitchen tech we've tested in 2024",
    "description": "True, Engadget is a technology news and reviews site — but we have a number of staffers who love to cook and even more who love to eat. Over the years, we’ve tested, reviewed and just plain used hundreds of kitchen gadgets and devices, some of which are techy…",
    "url": "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_f2e68b08-b36c-49fb-85c2-fb72579a93cb",
    "urlToImage": null,
    "publishedAt": "2024-07-16T15:30:30Z",
    "content": "If you click 'Accept all', we and our partners, including 236 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"
},
{
    "source": {
        "id": null,
        "name": "Yahoo Entertainment"
    },
    "author": "Sarah Fielding",
    "title": "Apple's M3 iMac is down to a record-low price",
    "description": "MacBooks are great, but if you're like me, then having to hunch over one brings back and neck pain. An iMac is a perfect though costly solution, but right now, it's a bit more affordable (emphasis on a bit). Apple's 2023 iMac with an M3 chip is down from $1,2…",
    "url": "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_52832731-cb6b-47b0-be49-a5d366204c52",
    "urlToImage": null,
    "publishedAt": "2024-07-25T13:06:21Z",
    "content": "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"
}
  ];
  
  export default placeholderArticles;
  